### ISSUE TITLE
Einlesen der DICOM-Daten in ITK oder VTK

### ISSUE THREAD

**Issue by LifY05** [Bas94/SMfMIA#1]
Im Repo existiert schon eine Klasse, die ITK nutzt um DICOM-Series einzuladen. Hier muss geschaut werden, ob die Loaderfunktion so funktioniert und verwendet werden kann.

**Comment by Elke94** [comment]
Zur Zeit gibt es noch keine Abfrage, wenn der ausgewählte Ordner keine DICOM Dateien enthält. Wird dann von VTK abgefangen. Aber weiß leider nicht wie man das geschickt abfragen kann.
