### ISSUE TITLE
Anzeigen der Schichtdaten in 2D

### ISSUE THREAD

**Issue by LifY05** [Bas94/SMfMIA#2]
Gut wäre es hier einen Viewer zu haben, bei dem man durch den Datensatz scrollen.
Optional:
* Umschalten der Sicht (Coronal, Sagital, Axial)

**Comment by Elke94** [comment]
Upps mit meinem letzten Commit hab ich alle Unterordner von 3rd-party gelöscht, hab die wohl mit in die gitignore gepackt :D  @Bas94  kannst du das rückgängig machen?^^

**Comment by Bas94** [comment]
@Elke94 sieht doch alles gut aus. Du hast sie nicht gelöscht, sondern in die .gitignore eingefügt. Außerdem hat dein Git-System wohl erkannt, dass die 3rd-party-Libraries auch git-Repos sind und diese dann sogar als submodule ins git-Repo eingefügt (was an sich sogar richtig ist). Kaputt ist nichts. Jedenfalls sehen die Commit-Diffs alle gut aus.
