### ISSUE TITLE
Maskenblending über den Datensatz

### ISSUE THREAD

**Issue by LifY05** [Bas94/SMfMIA#4]
Gut wäre eine Anzeige innerhalb des VIewers, bei dem man Masken über den Datzensatz legen kann

**Comment by Bas94** [comment]
Soweit steht hier die Grundfunktionalität. Es können Masken als Overlays in beliebiger Farbe angezeigt werden. Ein kleineres Problem besteht aber noch: Wenn man den Window/Level verändert, dann verändert sich das Overlay in unerwarteter Art und Weise. 
Mir ist aber noch nicht klar, wieso das passiert. Das muss irgendwas mit den Interna der Elternklasse vtkResliceImageViewer bzw vtkImageViewer2 zu tun haben.
